baseURL = "https://www.example.com/"
languageCode = "en-us"
title = "Chillpreneur"
summaryLength = 20

[module]
[[module.imports]]
path = "github.com/splatrac/chillpreneur"

[module.hugoVersion]
extended = true
min = "0.124.0"

[[module.mounts]]
source = "assets"
target = "assets"

[params]
title = "Up Business"
description = "We specialize in providing services to desing websites, applications, build and maintain business for customers."
# images = ["images/hero-image.png"]
logo = "logo.png"
location = [
    "3891 Ranchview Dr. Richardson, California 62639",
    "4517 Washington Ave. Manchester, Kentucky 39495",
]
contact = ["trungkienspktnd@gamail.com", "207.555.0119"]
copyright = "Â© 2022 Up Business All Rights Reserved"

[params.favicons]
themeColor = "#FFFFFF"
backgroundColor = "#FFFFFF"
faviconColor = "#000000"

[params.social]
dribbble = "#"
instagram = "#"
facebook = "#"
twitter = "#"

[[menus.main]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.main]]
name = "How we work"
url = "/#"
weight = 2

[[menus.main]]
name = "Our team"
url = "/#"
weight = 3

[[menus.main]]
name = "Pricing"
identifier = "pricing"
weight = 4
[[menus.main]]
parent = "pricing"
name = "Web"
url = "/pricing/web"
weight = 1

[[menus.main]]
parent = "pricing"
name = "Marketing"
url = "/pricing/marketing"
weight = 2

[[menus.main]]
parent = "pricing"
name = "Hardware"
url = "/pricing/hardware"
weight = 3

[[menus.main]]
name = "Blog"
url = "/blog"
weight = 5

[[menus.buttons]]
name = "Book a call"
url = "/#"
weight = 5
pre = "btn btn-primary text-light"

[[menus.footer]]
name = "Home"
url = "/#hero"
weight = 1

[[menus.footer]]
name = "How we work"
url = "/#"
weight = 2

[[menus.footer]]
name = "Our team"
url = "/#"
weight = 3

[[menus.footer]]
name = "Pricing"
url = "/#"
weight = 4

[[menus.footer]]
name = "Blog"
url = "/blog"
weight = 5

[taxonomies]
series = "series"
tags = "tags"
